# Generated by Django 2.2 on 2025-06-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsAccess',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('view_name', models.CharField(max_length=100, unique=True)),
                ('view_desc', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'View Access',
                'verbose_name_plural': 'Views Access',
                'db_table': 'views_access',
            },
        ),
        migrations.CreateModel(
            name='UserViewPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.IntegerField(blank=True, null=True)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ViewsAccess')),
            ],
            options={
                'verbose_name': 'User View Permission',
                'verbose_name_plural': 'User View Permissions',
                'db_table': 'user_view_permission',
                'unique_together': {('user_id', 'view')},
            },
        ),
    ]
